### ISSUE TITLE
2K2K dataset rendering

### ISSUE THREAD

**Issue by markkim1115** [SangHunHan92/2K2K#10]
Hello, thanks for the sharing your code and dataset.

I have downloaded 2K2K dataset, and ran the rendering code.

For the back-side image and depth generation, the code looks assigning the back-side color to the silhouette from front's view's mask.

But, In actual perspective setting, I think If the back-side is rendered from back camera view, front image and back image may not be matched in their silhouette.

Why did you not rendered back-side image from another back camera view, but generated using the implementation you provided in render_util.py?

If both side's images are not aligned, back normal generation does not work?

**Comment by SangHunHan92** [comment]
I know Opengl place the camera behind the mesh and additionally render the back face.
In contrast, our rendering method shoots rays from the front to create depth and images for the back. So it shares the front and back masks.
