### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by M1racle-milk** [SangHunHan92/2K2K#12]
I got an error when I run render.py to process the dataset. I ran the program with 16G RAM and a single RTX3060 GPU, and it can't work in colab with free T4 GPU as well.
Do I need a more powerful device?

Error:"numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.63 GiB for an array with shape (117683045, 3) and data type  float64"

**Comment by M1racle-milk** [comment]
I reset the cam_res=256, it seems work.

**Comment by GuiYu-wq** [comment]
Hello, how long does it take you to render an image with cam_res=256 running? I am under cam_res=2048, and there is no response in 12 hours

**Comment by M1racle-milk** [comment]
I rendered the smaller dataset and it took about 10 minutes with cam_res=512 per mesh.

**Comment by SangHunHan92** [comment]
I apologize for the very late reply.
Based on res=2048, I consume 300MB of GPU Memory and 18GB of GPU Memory.
Additionally, rendering per object takes approximately 8 minutes and 30 seconds.

**Comment by GuiYu-wq** [comment]
@M1racle-milk Hi, may I add your wechat to discuss? This is my wechat: 16601537087, thank you very much!

**Comment by M1racle-milk** [comment]
@GuiYu-wq The main problem I encountered was insufficient memory, which caused the program to crash at certain points. After reducing the resolution (to 256), and using the smaller dataset, the program was able to run, but the speed seemed to be related to the GPU performance.

**Comment by GuiYu-wq** [comment]
@M1racle-milk @SangHunHan92 Hello, thank you very much for your reply! As for the rendering problem, I tried the resolution of 256,512,1024 on the A100 respectively, and the rendering time of a mesh with 7 angles was 10 minutes, 40 minutes, and 2 hours respectively. But when the resolution is 2048, my 1.8T memory is still not enough to kill the process, so I sincerely hope that the author can check the render code, thank you very much!
