### ISSUE TITLE
dataset request 

### ISSUE THREAD

**Issue by pengHTYX** [SangHunHan92/2K2K#14]
hi, I have sent the email attached with "2K2K Dataset Realease Agreement" for a few days. So how long will it take for me to get accessible to the datasets. thanks!

**Comment by SangHunHan92** [comment]
Hi, sorry for delay in sending datasets.
I'll talk with dataset manager and send you the dataset as soon as possible.

**Comment by SangHunHan92** [comment]
I spoke with the data manager yesterday and he said he has emailed all requests.

Have you not received the email yet?

**Comment by pengHTYX** [comment]
I have received the data yesterday. Thank you very much.
