### ISSUE TITLE
How to get 2K2K datasets keypoints file(.npy) ?

### ISSUE THREAD

**Issue by qiyun71** [SangHunHan92/2K2K#15]
Hello, thank you for your nice work! I have some quesions about the keypoints file:
1) There are 2,000 training meshes, but there are only 1,000 Keypoints files(.mat) provided in https://github.com/ketiVision/2K2K
2) I found in the ReconDataset code that I need to load the keypoints file in npy format, but I did not find the code on how to convert the keypoints file in mat format to npy format.

I want to know when the rest of the dataset will be available, and can you give me some tips on how to convert the mat files into npy files? Thank you!

**Comment by richlaji** [comment]
Hello, I have also encountered this problem. I have just finished rendering the image and want to know how to obtain the keypoints.  Using OpenPose or download the keypoints from [https://github.com/ketiVision/2K2K](url)? By the way, only 909 .mat files were downloaded from the dropbox.

**Comment by qiyun71** [comment]
@richlaji I use openpose to generate keypoints files for each rendered image, then I write a scripts to convert .json files to .npy files based on _op_json_to_numpy_ in _test_02_model.py_.

**Comment by richlaji** [comment]
Thank you!!!
