### ISSUE TITLE
Which version of SMPL-X models should I download

### ISSUE THREAD

**Issue by GuiYu-wq** [SangHunHan92/2K2K#17]
Hello, thank you so much for your excellent work! Which version of SMPL-X models should I download from the official website?

**Comment by SangHunHan92** [comment]
Sorry for the late reply.
You can just use original version of SMPL-X.

![392847](https://github.com/SangHunHan92/2K2K/assets/38457117/7ce334cb-faae-4319-ba56-5052d3aa1ed8)

**Comment by GuiYu-wq** [comment]
Thank you very much!
