### ISSUE TITLE
Render Dataset  2k2k

### ISSUE THREAD

**Issue by xiangli93** [SangHunHan92/2K2K#2]
Could you share the code for rendering image and depth on the 2K2K dataset?

**Comment by SangHunHan92** [comment]
I am sorry for the delay in answering to the CVPR conference.
We were going to upload the rendering code with the completed 2K2K 3D keypoint file next month. 
If you want the code to render only the image and depth, I'll work on it and post it within this week.

**Comment by SangHunHan92** [comment]
Sorry for the late reply due to attending the CVPR conference.
We were going to upload the rendering code with the completed 2K2K 3D keypoint file next month.
If you want the code to render only the image and depth, I'll work on it and post it within this week.

**Comment by SangHunHan92** [comment]
I have updated rendering code for 2K2K dataset. Once the dataset is ready, the images and depth will be available for training.
