### ISSUE TITLE
Training is ok, but there is a problem during inference

### ISSUE THREAD

**Issue by richlaji** [SangHunHan92/2K2K#21]
Hi
    I try to train the model with 2k2k dataset and use black background only. It seems ok in tensorboard during the phase 1.
![image](https://github.com/SangHunHan92/2K2K/assets/10303294/25f99a22-d621-43a1-ab4a-16c904bd4db2)
upper normal:
![image](https://github.com/SangHunHan92/2K2K/assets/10303294/b35c9b2f-dbce-4141-9cad-3c25a48f70c6)
    During the inference, it is work well when I set the model.train() and the model output fail with model.eval()
![image](https://github.com/SangHunHan92/2K2K/assets/10303294/73a06303-1d0b-44c7-99c9-1b84a4b7250d)
    Could you give me some advices. Thank you!

**Comment by SangHunHan92** [comment]
(1) It seems to me that the upper normal is not completely shaped. It seems like that the network needs more training.

(2) It seems strange that train and eval have different results. 
Can you check the results of down normal, which is used as input to part-wise normal prediction? 
I think you need to check whether the down normal background has been removed.
