### ISSUE TITLE
Getting a 3d model from a photo from behind

### ISSUE THREAD

**Issue by avbelob** [SangHunHan92/2K2K#22]
Hello!
Thank you for your wonderful work!
Can you please tell me if I can somehow get a 3d model of person from a photo from behind? I want to try to combine the results from two photos of one person (front and back) to get more complete information for my 3d model.

**Comment by SangHunHan92** [comment]
I guess you can train model using photo from behind.

If you render the 3D model from behind, you can get images, normals, and depth maps of backside.
After then, you can train the back depth from the rendered back image, you will get the results you want.

**Comment by avbelob** [comment]
Thank you for your answer!
