### ISSUE TITLE
down_normal_back_pred and down_normal_front_pred are black images

### ISSUE THREAD

**Issue by ZhenhuiL1n** [SangHunHan92/2K2K#26]
Hi, 

I am retraining 2K2K using the 2K2K dataset in tensorboard. Everything works fine except the down_normal_front_pred and down_normal_back_pred are black images, as shown here, and the ground truth for it seems fine. Did you encounter this problem during training?

![image](https://github.com/SangHunHan92/2K2K/assets/56009715/3fc994a6-d7f9-49b1-83fc-03dd05465c23)
![image](https://github.com/SangHunHan92/2K2K/assets/56009715/8e737b2c-361b-4584-970a-cb1aec6cad1b)

**Comment by SangHunHan92** [comment]
Hi.

I experienced similar to what you said, that the normal map is sometimes predicted with a different color, or trained with a black image.
In this case, I had to retrain from scratch and check if the output is generated properly after about 200~300 steps.
