### ISSUE TITLE
pretrained model download error

### ISSUE THREAD

**Issue by niyunsheng** [SangHunHan92/2K2K#3]
The link https://github.com/SangHunHan92/2K2K/releases/download/Checkpoint/ckpt_bg_mask.pth.tar is not avialable now.

When will it be downloaded?

**Comment by SangHunHan92** [comment]
I removed the checkpoint trained with the RenderPeople, THuman2.0, and 2K2K datasets due to lisencing issue.
I will upload the checkpoint after training mesh with the watermark and resolving the license.
