### ISSUE TITLE
3D obj texture

### ISSUE THREAD

**Issue by jerett** [SangHunHan92/2K2K#4]
Thank you for your excellent work. I have two questions:

1. Does the exported obj come with texture? Or does the network inference include a texture part?
2. When will your pre-trained model be available for testing?

**Comment by SangHunHan92** [comment]
Thanks for your interest in my research!
1. My network only predicts surfaces, and textures come from images.
2. I first used the MIT license, but research result using human datasets cannot be used for commercial purposes. 
Therefore, I am looking for another license to replace the MIT license. 
As soon as I find a suitable license, I will share the pre-trained checkpoint.
