### ISSUE TITLE
Can we use custom data?

### ISSUE THREAD

**Issue by NaToh5** [SangHunHan92/2K2K#6]
Hi, can I use my own data to test on your model? If I can, what are the requirements for my data? 

Another question is that does your model can output texture and apply on the obj? 

Thanks.

**Comment by SangHunHan92** [comment]
Sure! You can use any 3D human mesh dataset for model training. Just check the image and depth map of the human model.

Our model just output depth map and 3d mesh surface, not texture. You should use input texture to colorize front view of mesh.

**Comment by NaToh5** [comment]
Sorry could you give me more detail for custom dataset? 
To test it on your dataset first of I will need my own input image , 3D key points, 2D key points?  How can I extract 3D key points? And also how did you extract the colorize texture?

Thank you.

**Comment by SangHunHan92** [comment]
Oops! Sorry, I misunderstood you question.
You only need image and 2d keypoint.
Please refer here :
https://github.com/SangHunHan92/2K2K#model-test

I also extract texture to colorize depth pointcloud in my code. It colorize front view of mesh.

**Comment by NaToh5** [comment]
Thank you again your reply. 
Could you also me share a code with me about extracting the texture and apply it?

Thanks.

**Comment by SangHunHan92** [comment]
Never mind that.
It is already implemented in my code.

**Comment by NaToh5** [comment]
Oh so when I run the command from test the model, it will output the obj file with textured?

**Comment by SangHunHan92** [comment]
Yes. After run test_03_model.py, you can get obj mesh.

**Comment by NaToh5** [comment]
Thank you I appreciate your help.
