### ISSUE TITLE
Question for Texture

### ISSUE THREAD

**Issue by NaToh5** [SangHunHan92/2K2K#7]
Hello I already run these two commands and got the result but the ply or obj file seems to don't have texture, did I do something wrong ? 

```
python test_02_model.py --load_ckpt {checkpoint_file_name} --save_path {result_save_folder}
python test_03_model.py --save_path {result_save_folder}
```
**Results**
![image](https://github.com/SangHunHan92/2K2K/assets/134680400/4905931f-a2d3-44ff-8f51-fbac2fd370b8)

**Comment by SangHunHan92** [comment]
![image](https://github.com/SangHunHan92/2K2K/assets/38457117/64922746-496d-4204-b6eb-3f9e0aa76197)

1. It seems you don't run test_03_model.py. After run test_03_model.py, It generate "output_objs" folder.
2. I changed code in test_03_model.py to add vertex color. Please replace test_03_model.py file and try again.

**Comment by SangHunHan92** [comment]
that's weird
If you run test_02_model.py, there should be "test" folder under ./result.

After that, running the code below :
python test_03_possion.py --save_path ./result --proj_name test
I think my code misunderstood a bit.

**Comment by NaToh5** [comment]
Firstly I run this : python test_02_model.py --load_ckpt ckpt_bg_mask.pth.tar --save_path C:\Users\ADMIN\Desktop\2K2K\output

And then when I run python test_03_possion.py --save_path ./result --proj_name test

**Error** 
**Traceback (most recent call last):
  File "test_03_poisson.py", line 56, in <module>
    main(args.save_path, args.proj_name)
  File "test_03_poisson.py", line 25, in main
    pc_list = os.listdir(pc_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: './result\\test\\output_plys'**

**Comment by NaToh5** [comment]
Sorry even I update the code with yours. It still don't have texture . 

![image](https://github.com/SangHunHan92/2K2K/assets/134680400/337e8fc0-e923-4670-bd75-8acb4eb4a45a)

**Comment by SangHunHan92** [comment]
![image](https://github.com/SangHunHan92/2K2K/assets/38457117/eab2e5dc-7510-4edd-a2b4-d1168f4a0983)

Did you open it with Meshlab ??
https://www.meshlab.net/
You can see texture in Meshlab.

![image](https://github.com/SangHunHan92/2K2K/assets/38457117/b705617b-d8b6-4c5b-842d-b64e7ac7db66)
Alternatively, you can check if the vertex color exists by opening the obj file with Notepad.
The 2nd to 4th rows represent 3d coordinates, and the 5th to 7th rows represent texture.

**Comment by NaToh5** [comment]
Ah yes , it is working on Mesh lab, I don't know why it didn't show in 3D software like Blender. 

And also this backside have error ? I know that the input image didn't include the backside of  a person. Is it possible to test both front and backside image to get fully texture ? 

![image](https://github.com/SangHunHan92/2K2K/assets/134680400/ee034afc-f1ff-4fef-aa3b-85bd7a324982)

**Comment by SangHunHan92** [comment]
Probably, I know that in Blender, you need a texture map to apply texture to the mesh. 
However, transforming vertex colors into texture maps is a difficult task.

Also, since the test image does not have a texture of the backside, I replaced the backside with the frontside.
If you have a backside image you can modify the code to apply the backside texture.

**Comment by NaToh5** [comment]
Thank you for helping me again, could you give me a code to change the backside please if possible? 

I will really appreciate it.

**Comment by SangHunHan92** [comment]
![image](https://github.com/SangHunHan92/2K2K/assets/38457117/df2ffdc5-f0c3-44fd-8fe7-aaa910fd4856)

You can change 337 line of test_02_model.py to replace backside texture.
Just do that, and the problem will be solved.

**Comment by NaToh5** [comment]
Thank you. Could you also give me some suggestion to get the better quality texture or obj file ? 

Thanks

**Comment by SangHunHan92** [comment]
I think good background remover, and unblurred image will show good results.
Maybe an image enhancement tool might be useful, but I haven't tested this.

**Comment by NaToh5** [comment]
Thank you @SangHunHan92
