### ISSUE TITLE
numpy.linalg.LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by xiangli93** [SangHunHan92/2K2K#8]
numpy.linalg.LinAlgError: SVD did not converge？

**Comment by SangHunHan92** [comment]
![image](https://github.com/SangHunHan92/2K2K/assets/38457117/5fc13084-522e-4253-9105-11ed16f7142b)

Where did it happen?
I guess it probably happened in calculating the init_affine matrix at the 2d keypoint.

Could you check once if the 2d keypoint was properly extracted?

**Comment by xiangli93** [comment]
When the input image is the human body from the back, it will occurs the following error: 
                   x = np.dot(np.linalg.pinv(A), b)
![image](https://github.com/SangHunHan92/2K2K/assets/79239875/8ae3aea0-b3f8-4eb2-931f-53532829be8d)

**Comment by xiangli93** [comment]
When the input image is the human body from the back, the following error occurs.
![image](https://github.com/SangHunHan92/2K2K/assets/79239875/f68e6d07-629e-4b37-bb12-55279d49fced)
