### ISSUE TITLE
Output hand result is not good 

### ISSUE THREAD

**Issue by TharHtetAungg** [SangHunHan92/2K2K#9]
Hi, my output result is not good, especially in Hands. Could you give me some advice to get good quality hand ? 

![image](https://github.com/SangHunHan92/2K2K/assets/79152768/244fd18a-3789-4476-b848-8a3ba3ec1870)

**Comment by SangHunHan92** [comment]
My model is very sensitive to borders in the foreground and background.
Clearer boundaries produce better results.

And, I've noticed that in-the-wild images with a lot of blur don't have much detail.
I've also confirmed that image sharpening or image enhancers make the results slightly better.

First of all, I uploaded another version of Checkpoint with good details, so would you like to test it?
https://github.com/SangHunHan92/2K2K/releases/download/Checkpoint2/ckpt_alldataset_bg_blurmask_phase3.pth.tar

But I just did some tests, the hand is still hard to reconstruct.
I show some results of in-the-wild images.
![image](https://github.com/SangHunHan92/2K2K/assets/38457117/4f758f68-ea3a-4014-a79d-2663a45a1f99)

**Comment by TharHtetAungg** [comment]
Thank you for your reply. 
Yes, I will happily test your new pre-trained model, but it seems to be the same as the previous one on Hand. 

I have another issue about your output obj model seems to have a lot of vertices count which I cannot use on Unity. Do you have any suggestion to reduce the vertices count ?

**Comment by SangHunHan92** [comment]
Can you add these lines in test_02_model.py?

front_depth[1::2, 1::2, :], front_depth[0::2, 1::2, :], front_depth[1::2, 0::2, :]  = 0, 0, 0
back_depth[1::2, 1::2, :],  back_depth[0::2, 1::2, :],  back_depth[1::2, 0::2, :] = 0, 0, 0

![image](https://github.com/SangHunHan92/2K2K/assets/38457117/5b0aaad2-71c7-445a-b9d8-4b64e081b5cf)

It will sample vertices unifromly.

**Comment by TharHtetAungg** [comment]
Sorry, that code mean to reduce the vertices count ? If yes, I think the vertices count is still not reducing after I run that code. 
Thanks.

**Comment by SangHunHan92** [comment]
![image](https://github.com/SangHunHan92/2K2K/assets/38457117/cdff5965-bdbe-43aa-ade2-d49af2074373)


That's weird.
Applying this reduces the number of vertices to 1/4.

**Comment by TharHtetAungg** [comment]
Yes, the original vertices have 700K  and the new vertices have 659K, it looks like reduces but still cannot use with that amount of vertices. 
Thanks.

**Comment by SangHunHan92** [comment]
Reduces too little.
That code samples the depth map half by column and half by row.
Only about 1/4 should remain.

**Comment by TharHtetAungg** [comment]
I will check it again. And also could you give me some tips about how can we use this model in Unity ? The model in unity doesn't have color or texture. Look like it only show the color on Mesh lab.

**Comment by SangHunHan92** [comment]
![image](https://github.com/SangHunHan92/2K2K/assets/38457117/c33159e2-a859-4cdd-84fc-034d0dce7d06)

I find answer.
Set depth=9 of surface_reconstruction_screened_poisson in test_03_poisson.py

**Comment by SangHunHan92** [comment]
I know that in Unity or Blender, a texture map (like png or jpg) is required to apply texture (color) to the mesh.
I guess I'll have to find a way to convert the vexture color to a texture map for this.

**Comment by TharHtetAungg** [comment]
It will be great if you can convert the vetrex color to texture map. I am waiting for you update. 

Thank you for help me.
